name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  spm-15:
    name: Build Xcode 15
    runs-on: macos-13
    strategy:
      matrix:
        platforms: [
          'iOS_17,watchOS_10',
          'macOS_14,tvOS_17',
        ]
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_15.0.1.app/Contents/Developer
      - name: Build and Test Framework
        run: Scripts/build.swift ${{ matrix.platforms }}
      - name: Prepare Coverage Reports
        run: ./Scripts/prepare-coverage-reports.sh
      - name: Upload Coverage Reports
        if: success()
        uses: codecov/codecov-action@v3
  spm-15-swift:
    name: Swift Build Xcode 15
    runs-on: macos-13
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_15.0.1.app/Contents/Developer
      - name: Build and Test Framework
        run: xcrun swift test -c release -Xswiftc -enable-testing
